### PR TITLE
updates to the github tutorial

### PR DESCRIPTION
**Pull request by choldgraf**
@naupaka @mpacer

### CODE REVIEW

**Review by burkesquires — APPROVED** [review]
Chris expanded on the material and converted to slides for use with RISE

**Comment by hlapp** [comment]
@burkesquires can you explain how you resolved the merge conflict? It seemed entirely irreconcilable to me. I think I overwrote whatever changes you may have made, but the original commit from @choldgraf should still be in his fork. When you merged I was in the process of applying parts of the diff that I didn't see present already, see e104422744ae326064bb200775cfcb2910fee5ee.

(As an aside, please don't merge pull requests, especially those on serious merge conflict, 1 hours before the lesson is taught by someone else across the continent. 😅 ) 

I think the notebook as an episode (as opposed to slides) works fine. Not sure why that would be worth changing to slides.

**Comment by burkesquires** [comment]
Hi @hlapp,
So sorry about the timing. I resolved the merge conflict by combining the two statements. Your looked like an overview and Chris' looks like some additional details and they seemed to fit together well. Sorry if I missed something.

**Comment by naupaka** [comment]
I think the idea of some of @choldgraf's changes were to be able to tag the cells to either export to slides, to student notebooks, or to the narrative. I also tried to merge but there is a bug so nbdime can't handle it and I couldn't do it manually, so I was just going to add the content to one of the notebooks by hand and use that.

**Pull request merged**
